package main

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/rankegraph/ranke-go"
	"github.com/rankegraph/ranke-go/internal/vectors"
	"github.com/stretchr/testify/require"
)

// The artifacts are worth nothing if their expectations are merely asserted, so the
// generator's own claims are checked here against the library that must uphold them.

// testProvenance is fixed, so the reproducibility check compares the artifacts
// rather than the wall clock the real run stamps them with.
var testProvenance = vectors.Provenance{
	Generator:   generatorPath,
	Version:     "v0.0.0-test",
	GeneratedAt: "2026-01-01T00:00:00Z",
}

// generate runs the generator into a temp dir and reads back its manifest.
func generate(t *testing.T) (string, vectors.Manifest) {
	t.Helper()
	dir := t.TempDir()
	require.NoError(t, run(context.Background(), dir, testProvenance))

	m, err := vectors.Load(dir)
	require.NoError(t, err)
	return dir, *m
}

// TestVectorsAreReproducible: the set is regenerated by hand and committed, so a
// re-run must produce identical bytes or every regeneration is a spurious diff.
func TestVectorsAreReproducible(t *testing.T) {
	a, _ := generate(t)
	b, _ := generate(t)

	walk := func(root string) map[string]string {
		out := map[string]string{}
		require.NoError(t, filepath.Walk(root, func(p string, info os.FileInfo, err error) error {
			if err != nil || info.IsDir() {
				return err
			}
			body, err := os.ReadFile(p)
			if err != nil {
				return err
			}
			rel, err := filepath.Rel(root, p)
			if err != nil {
				return err
			}
			out[rel] = string(body)
			return nil
		}))
		return out
	}
	require.Equal(t, walk(a), walk(b), "two runs of the generator must agree byte for byte")
}

// TestClaimCasesHoldAsDescribed verifies every claim case through the library, using
// the same checker the conformance gate runs, so the two cannot disagree.
func TestClaimCasesHoldAsDescribed(t *testing.T) {
	dir, m := generate(t)

	outcomes, err := vectors.CheckClaims(context.Background(), dir, &m)
	require.NoError(t, err)
	require.Len(t, outcomes, len(m.Claims))
	for _, o := range outcomes {
		t.Run(filepath.Base(o.File), func(t *testing.T) {
			require.Truef(t, o.Holds(), "expected verify=%v, got %v (%s) — %s",
				o.Expected, o.Accepted, o.Reason, o.Why)
		})
	}
}

// TestBookmarkCasesHoldAsDescribed verifies every 𝒰_hist case through the library,
// using the same checker the conformance gate runs.
func TestBookmarkCasesHoldAsDescribed(t *testing.T) {
	dir, m := generate(t)
	require.NotEmpty(t, m.Bookmarks)

	outcomes, err := vectors.CheckBookmarks(context.Background(), dir, &m)
	require.NoError(t, err)
	require.Len(t, outcomes, len(m.Bookmarks))
	for _, o := range outcomes {
		t.Run(filepath.Base(o.File), func(t *testing.T) {
			require.Truef(t, o.Holds(), "expected verify=%v, got %v (%s) — %s",
				o.Expected, o.Accepted, o.Reason, o.Why)
		})
	}
}

// TestBookmarkSlotsAreDistinctPerList: a downstream implementation loads the whole set
// into one 𝒰_hist, so two cases sharing a slot would file one record under the other's
// key — and a rejected record landing in a valid list would fail it for the wrong
// reason. Cases of one list are the exception: sharing the seed is what makes them one.
func TestBookmarkSlotsAreDistinctPerList(t *testing.T) {
	_, m := generate(t)
	require.NotEmpty(t, m.Bookmarks)

	seen := map[string]string{}
	for _, c := range m.Bookmarks {
		if prev, dup := seen[c.Slot]; dup {
			require.Failf(t, "two cases share a slot", "%s and %s both sit at %s", prev, c.File, c.Slot)
		}
		seen[c.Slot] = c.File
	}
}

// TestToyGraphIsAnArchive: the set carries a bookmark list, and only an archive has
// one. Opening it the way §Backup prescribes — one bookmark id to the latest head it
// records — must reach a branch table (`V-ARCHIVE`). CheckClaims verifies claim by
// claim, so this archive-scoped rule is out of its reach entirely.
func TestToyGraphIsAnArchive(t *testing.T) {
	ctx := context.Background()
	dir, m := generate(t)

	u := ranke.NewMemoryUniverse()
	for _, c := range m.Claims {
		if !c.Verify {
			continue
		}
		cl, err := vectors.Decode(dir, c)
		require.NoError(t, err)
		require.NoError(t, u.PutClaims(ctx, []ranke.Claim{cl}))
	}

	marks, err := vectors.OpenList(ctx, dir, &m, "archive", u)
	require.NoError(t, err)
	latest, err := marks.Latest(ctx)
	require.NoError(t, err)
	require.NotNil(t, latest.Head(), "the bookmark list must resolve to the head it records")

	arc, err := ranke.NewArchive(ctx, u, latest.Head())
	require.NoError(t, err)
	run, err := arc.Verify(ctx)
	require.NoError(t, err)
	run.Wait()
	require.NoError(t, run.Err())
	require.Empty(t, run.Failures(), "the head the list records must open as a valid archive")
}

// TestRejectionIsNotMereAbsence is the control the rejected cases need: only the
// root contributor is stored, yet source-note still verifies. So a rejection above
// is the case's own defect, not the claim being unknown to the universe.
func TestRejectionIsNotMereAbsence(t *testing.T) {
	ctx := context.Background()
	dir, m := generate(t)

	u := ranke.NewMemoryUniverse()
	root := filepath.Join("claims", "root-contributor.cbor")
	for _, c := range m.Claims {
		if c.File == root {
			cl, err := vectors.Decode(dir, c)
			require.NoError(t, err)
			require.NoError(t, u.PutClaims(ctx, []ranke.Claim{cl}))
		}
	}

	note := filepath.Join("claims", "source-note.cbor")
	for _, c := range m.Claims {
		if c.File == note {
			require.True(t, vectors.Accepts(ctx, u, dir, c),
				"an unstored claim verifies once its contributor resolves")
		}
	}
}

// TestContentCasesHoldAsDescribed checks each blob against the hash it is filed
// under, which is the whole of content integrity (§5.10).
func TestContentCasesHoldAsDescribed(t *testing.T) {
	dir, m := generate(t)
	require.NotEmpty(t, m.Content)

	outcomes, err := vectors.CheckContent(dir, &m)
	require.NoError(t, err)
	for _, o := range outcomes {
		t.Run(filepath.Base(o.File), func(t *testing.T) {
			require.Truef(t, o.Holds(), "expected verify=%v, got %v (%s) — %s",
				o.Expected, o.Accepted, o.Reason, o.Why)
		})
	}
}

// TestManifestRecordsItsProvenance: the set is fetched, not pinned, so the manifest
// has to say which release produced it and when.
func TestManifestRecordsItsProvenance(t *testing.T) {
	_, m := generate(t)
	require.Equal(t, testProvenance, m.Provenance)

	// The real run reports the module version it was invoked as, which is a release
	// only when fetched as one.
	require.NotEmpty(t, generatorVersion())
}

// TestEveryReasonIsExercised keeps the set honest as it grows: a reason code that
// no case carries is a failure mode nobody is testing. It reads vectors.AllReasons
// rather than a list of its own — the hand-kept copy that used to live here could
// only grow when someone remembered, which is how `V-TIME` arrived with no case.
func TestEveryReasonIsExercised(t *testing.T) {
	_, m := generate(t)

	seen := map[string]bool{}
	for _, c := range m.Claims {
		seen[c.Reason] = true
	}
	for _, c := range m.Content {
		seen[c.Reason] = true
	}
	for _, c := range m.Bookmarks {
		seen[c.Reason] = true
	}
	for _, want := range vectors.AllReasons {
		require.Truef(t, seen[want], "no case carries reason %q", want)
	}
}

// decodeSentinel is the error a reason must produce, for the reasons a record is
// refused at DECODE. The rest are refused by the closure verifier, where the failure
// is a set rather than one error, so they are not in reach of this assertion.
var decodeSentinel = map[string]error{
	vectors.ReasonTimestampForm: ranke.ErrTimestampForm,
	vectors.ReasonBothContent:   ranke.ErrContentBothSlots,
	vectors.ReasonDatedForm:     ranke.ErrDatedForm,
}

// TestRejectedCasesFailForTheirStatedReason: rejection alone is cheap — a case with
// two defects, or one refused by an unrelated check, still reads as passing. Where a
// reason names a decode-time error, the case must produce THAT error.
func TestRejectedCasesFailForTheirStatedReason(t *testing.T) {
	dir, m := generate(t)

	var checked int
	for _, c := range m.Claims {
		want, ok := decodeSentinel[c.Reason]
		if !ok {
			continue
		}
		t.Run(filepath.Base(c.File), func(t *testing.T) {
			require.False(t, c.Verify, "a case naming a refusal must expect one")
			_, err := vectors.Decode(dir, c)
			require.ErrorIs(t, err, want)
		})
		checked++
	}
	require.Equal(t, len(decodeSentinel)+2, checked,
		"every V-TIME, V-CONTENT and V-DATED case is covered here: three timestamps, "+
			"both slots, one dated")
}
