package main

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/flocko-motion/ranke-go"
	"github.com/flocko-motion/ranke-go/internal/vectors"
	"github.com/stretchr/testify/require"
)

// The artifacts are worth nothing if their expectations are merely asserted, so the
// generator's own claims are checked here against the library that must uphold them.

// testProvenance is fixed, so the reproducibility check compares the artifacts
// rather than the wall clock the real run stamps them with.
var testProvenance = vectors.Provenance{
	Generator:   generatorPath,
	Version:     "v0.0.0-test",
	GeneratedAt: "2026-01-01T00:00:00Z",
}

// generate runs the generator into a temp dir and reads back its manifest.
func generate(t *testing.T) (string, vectors.Manifest) {
	t.Helper()
	dir := t.TempDir()
	require.NoError(t, run(context.Background(), dir, testProvenance))

	m, err := vectors.Load(dir)
	require.NoError(t, err)
	return dir, *m
}

// TestVectorsAreReproducible: the set is regenerated by hand and committed, so a
// re-run must produce identical bytes or every regeneration is a spurious diff.
func TestVectorsAreReproducible(t *testing.T) {
	a, _ := generate(t)
	b, _ := generate(t)

	walk := func(root string) map[string]string {
		out := map[string]string{}
		require.NoError(t, filepath.Walk(root, func(p string, info os.FileInfo, err error) error {
			if err != nil || info.IsDir() {
				return err
			}
			body, err := os.ReadFile(p)
			if err != nil {
				return err
			}
			rel, err := filepath.Rel(root, p)
			if err != nil {
				return err
			}
			out[rel] = string(body)
			return nil
		}))
		return out
	}
	require.Equal(t, walk(a), walk(b), "two runs of the generator must agree byte for byte")
}

// TestClaimCasesHoldAsDescribed verifies every claim case through the library: the
// ones marked verify must pass the closure verifier, the rest must be refused.
func TestClaimCasesHoldAsDescribed(t *testing.T) {
	ctx := context.Background()
	dir, m := generate(t)

	// The universe holds what the set says is valid, so a case's contributor
	// resolves exactly when the set actually carries it.
	u := ranke.NewMemoryUniverse()
	for _, c := range m.Claims {
		if !c.Verify {
			continue
		}
		cl := load(t, dir, c)
		require.NoError(t, u.PutClaims(ctx, []ranke.Claim{cl}))
	}

	for _, c := range m.Claims {
		t.Run(filepath.Base(c.File), func(t *testing.T) {
			ok := accepts(ctx, t, dir, u, c)
			require.Equal(t, c.Verify, ok, "case %q: %s", c.File, c.Why)
		})
	}
}

// accepts reports whether the library takes the case's bytes under the case's id.
func accepts(ctx context.Context, t *testing.T, dir string, u ranke.Universe, c vectors.ClaimCase) bool {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(dir, c.File))
	require.NoError(t, err)

	id, err := ranke.ParseId(c.Id)
	if err != nil {
		return false // a malformed id is refused before any hashing
	}
	cl, err := ranke.DecodeClaim(id, raw)
	if err != nil {
		return false
	}
	g, err := ranke.NewGraph(ctx, u)
	require.NoError(t, err)
	if err := g.AddClaims(ctx, cl); err != nil {
		return false
	}
	run := g.Verify()
	run.Wait()
	return run.Err() == nil && len(run.Failures()) == 0
}

// load decodes a case's record under the id it is offered as.
func load(t *testing.T, dir string, c vectors.ClaimCase) ranke.Claim {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(dir, c.File))
	require.NoError(t, err)
	id, err := ranke.ParseId(c.Id)
	require.NoError(t, err)
	cl, err := ranke.DecodeClaim(id, raw)
	require.NoError(t, err)
	return cl
}

// TestRejectionIsNotMereAbsence is the control the rejected cases need: only the
// root contributor is stored, yet source-note still verifies. So a rejection above
// is the case's own defect, not the claim being unknown to the universe.
func TestRejectionIsNotMereAbsence(t *testing.T) {
	ctx := context.Background()
	dir, m := generate(t)

	u := ranke.NewMemoryUniverse()
	root := filepath.Join("claims", "root-contributor.cbor")
	for _, c := range m.Claims {
		if c.File == root {
			require.NoError(t, u.PutClaims(ctx, []ranke.Claim{load(t, dir, c)}))
		}
	}

	note := filepath.Join("claims", "source-note.cbor")
	for _, c := range m.Claims {
		if c.File == note {
			require.True(t, accepts(ctx, t, dir, u, c),
				"an unstored claim verifies once its contributor resolves")
		}
	}
}

// TestContentCasesHoldAsDescribed checks each blob against the hash it is filed
// under, which is the whole of content integrity (§5.10).
func TestContentCasesHoldAsDescribed(t *testing.T) {
	dir, m := generate(t)
	require.NotEmpty(t, m.Content)

	for _, c := range m.Content {
		t.Run(filepath.Base(c.File), func(t *testing.T) {
			blob, err := os.ReadFile(filepath.Join(dir, c.File))
			require.NoError(t, err)
			hash, err := ranke.ParseId(c.Hash)
			require.NoError(t, err)

			err = ranke.VerifyContent(hash, uint64(len(blob)), blob)
			require.Equal(t, c.Verify, err == nil, "case %q: %s", c.File, c.Why)
		})
	}
}

// TestManifestRecordsItsProvenance: the set is fetched, not pinned, so the manifest
// has to say which release produced it and when.
func TestManifestRecordsItsProvenance(t *testing.T) {
	_, m := generate(t)
	require.Equal(t, testProvenance, m.Provenance)

	// The real run reports the module version it was invoked as, which is a release
	// only when fetched as one.
	require.NotEmpty(t, generatorVersion())
}

// TestEveryReasonIsExercised keeps the set honest as it grows: a reason code that
// no case carries is a failure mode nobody is testing.
func TestEveryReasonIsExercised(t *testing.T) {
	_, m := generate(t)

	seen := map[string]bool{}
	for _, c := range m.Claims {
		seen[c.Reason] = true
	}
	for _, c := range m.Content {
		seen[c.Reason] = true
	}
	for _, want := range []string{
		vectors.ReasonOK, vectors.ReasonIDMismatch, vectors.ReasonWrongMessage,
		vectors.ReasonMalformedID, vectors.ReasonIdentitySign, vectors.ReasonNoContributor,
		vectors.ReasonHeightWrong, vectors.ReasonContentMismatch,
	} {
		require.Truef(t, seen[want], "no case carries reason %q", want)
	}
}
